version: "3"

volumes:
  db-data:

services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: aknms
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: admin123
 
  backend:
    image: arunpalani87/aknms-backend
    #image: karthik1836/aknms-backend
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - db

  frontend:
    image: arunpalani87/aknms-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
