version: "3"

networks:
  aknms-network:
    driver: bridge

volumes:
  db-data:

services:
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/aknms/data
    networks:
      - aknms-network
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: aknms
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: admin123

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - db-data:/data/db
    networks:
      - aknms-network
    ports:
      - 27017

  backend:
    image: arunpalani87/aknms-backend
    #image: karthik1836/aknms-backend
    container_name: backend
    networks:
      - aknms-network
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - mysql

  frontend:
    image: arunpalani87/aknms-frontend
    container_name: frontend
    networks:
      - aknms-network
    ports:
      - 3000:3000
    depends_on:
      - backend
